name: Generate Snake Animation

on:
  schedule:
    - cron: "0 0 * * *" # প্রতিদিন মধ্যরাতে চলবে
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  generate-snake:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: Platane/snk@v3
        id: snake-gif
        with:
          github_user_name: RabbiTheAnalyst
          outputs: |
            dist/snake.svg
            dist/snake-dark.svg?palette=github-dark
      - uses: crazy-max/ghaction-github-pages@v3
        with:
          target_branch: output
          build_dir: dist
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
